### PR TITLE
add addTeamRepo api to org

### PR DESCRIPTION
**Pull request by nicktesla**
ghorg.addTeamRepo will add a team to an organization's repo. Pretty straightforward. Would love to see this/something like this merged in soon :)

### CODE REVIEW

**Comment by pksunkara** [comment]
Sorry, you need to write this in coffee-script and then generate the javascript.

**Comment by nicktesla** [comment]
OK

**Comment by pksunkara** [comment]
And are you sure about having this api in the `org.js` file? What do you think of `team.js`?

**Comment by nicktesla** [comment]
team.js makes sense as well but its under Organizations on github: https://developer.github.com/v3/orgs/teams/#add-team-repo

Should I move it to team.js?

P.S. cake lib fails for me on OSX (I get an ENOENT error)

**Comment by pksunkara** [comment]
Leave it at org then. Try this command, `./node_modules/.bin/coffee -c -o lib src` instead of `cake lib`

**Comment by nicktesla** [comment]
OK done...check it out

**Comment by pksunkara** [comment]
Looks good except for the coffee-script version. Could you please fix those and I will merge this? Thanks.

**Comment by nicktesla** [comment]
coffee-script version?

**Comment by pksunkara** [comment]
If you look at the diff, you can see that you are using `1.7.1` instead of `1.8.0`

**Comment by nicktesla** [comment]
ha ok i think this is good?...P.S. how could you tell the version ...don't see it in the diff?

**Pull request merged**
