### PR TITLE
Check err before reading res. Fixes #186.

### LINKED ISSUE #186: Unhandled error
Getting this issue when network connection is down:

```
node_modules/octonode/lib/octonode/auth.js:111
            if (res.statusCode === 404) {
                   ^
TypeError: Cannot read property 'statusCode' of undefined
```

I guess you want to check that `err` is empty before reading `res`.
Let me know if you want a PR.

### PR DESCRIPTION
**Pull request by benweet**
That's my first coffeescript coding... Don't know how to compile that though.

### CODE REVIEW

**Comment by pksunkara** [comment]
Please run `node_modules/.bin/coffee -c -o lib src` to generated the javascript and amend the changes to the above commit.

**Comment by benweet** [comment]
Just did.

**Comment by pksunkara** [comment]
Please merge the 2 commits into a single one.

**Comment by benweet** [comment]
Done.

**Comment by pksunkara** [comment]
Thanks :smile:

**Pull request merged**
