### PR TITLE
Add support for getReference

### PR DESCRIPTION
**Pull request by richsong**
## Notes:
- Relatively simple change to add support for getReference

### CODE REVIEW

**Comment by pksunkara** [comment]
Please write coffeescript and then compile it.

**Comment by richsong** [comment]
Thank you for the fast feedback. I've never used coffescript. Could you translate for me?

**Comment by pksunkara** [comment]
Actually getting reference exists. https://github.com/pksunkara/octonode/blob/master/src/octonode/repo.coffee#L428

**Comment by richsong** [comment]
Oh interesting... Let me give that shot. I also figured out the coffeescript portion lol. Thanks again

**Comment by richsong** [comment]
@pksunkara - it turns out the `ref` method you were referring towards isn't exactly what i'm looking for. You will notice the difference in paths:
`@client.get "/repos/#{@name}/git/refs/#{ref}", (err, s, b)`
vs
`@client.get "/repos/#{@name}/branches/#{ref}", (err, s, b, h)`

Furthermore, I have written the solution in coffee script and compiled it as requested. Please let me know if there is anything else I could help with

**Comment by pksunkara** [comment]
https://github.com/pksunkara/octonode/pull/337/files#diff-2cbf4f4719438757db95186b1239e741R196

**Comment by richsong** [comment]
> https://github.com/pksunkara/octonode/pull/337/files#diff-2cbf4f4719438757db95186b1239e741R196

👍

**Pull request closed without merging**
