### PR TITLE
Updated Readme to include Async functions

### PR DESCRIPTION
**Pull request by Circuit8**
https://github.com/pksunkara/octonode/issues/314

### CODE REVIEW

**Comment by pksunkara** [comment]
Why did you add the second commit? I like the first one.

**Comment by Circuit8** [comment]
Hey sorry just read this, I think it contained an error

**Comment by tomsiwik** [comment]
I'm confused. I can't find any `<methodName>Async(...)` methods stated in the README.md. However, I see:

https://github.com/pksunkara/octonode/commit/5cbb4a437a9c67a84df5080efab43fc1f27f80a4

Now, how do I return a promise/async for the chained methods? 
`repo` is a promise, `repo(...).contents(...)` is not.

**Comment by pksunkara** [comment]
`repo(...).contentsAsync(...)`

**Pull request merged**
