### PR TITLE
remove explicit proxy config

### PR DESCRIPTION
**Pull request by homeyer**
request looks at [proxy environment variables by default](https://github.com/request/request#controlling-proxy-behaviour-using-environment-variables), and supports `HTTPS_PROXY` and `NO_PROXY`, not just `HTTP_PROXY`. Removing the explicit proxy config allows the environment properties to be consumed natively (and properly) by request.

Purpose: At Waffle.io, our on-premises version support proxy configuration. It's common to proxy requests to github.com, but not proxy requests to a GH:E install. Currently it's not possible to set a `NO_PROXY` configuration, because it hard codes the proxy to be the `HTTP_PROXY` value.

### CODE REVIEW

**Comment by pksunkara** [comment]
The diff looks good, but I am just wondering if #84 is still going to work.

**Comment by pksunkara** [comment]
Forgot to mention @joshrp here.

**Comment by homeyer** [comment]
When #84 was merged, [request was still at `2.27.x` in `package.json`](https://github.com/pksunkara/octonode/pull/84/files#diff-b9cfc7f2cdf78a7f4b91a753d10865a2R36). Proxy support landed in `2.38`: https://github.com/request/request/blob/master/CHANGELOG.md#v2380-20140722

Since octonode now depends on request `2.51`, #84 will still work.

**Comment by homeyer** [comment]
thanks @pksunkara! Would you mind bumping the version and publishing to npm?

**Comment by pksunkara** [comment]
Done. :smile:

**Comment by homeyer** [comment]
:+1:

**Pull request merged**
